application: labsfs
version: 1
runtime: python
api_version: 1

handlers:
 - url: /static
   static_dir: static

 - url: /remote_api
   script: /usr/local/google_appengine/google/appengine/ext/remote_api/handler.py
   login: admin

 - url: .*
   script: main.py
